source ~/.vimrc.shared
" directories ============================
set backupdir=~/.vim/backup//
set directory=~/.vim/swap//
set undodir=~/.vim/undo//
" ----------------------------------------
" color scheme ===========================
colorscheme tkiatd
" ----------------------------------------
" pkg manager: vim-pathogen ==============
call pathogen#infect()
" ----------------------------------------
" plugin: NERDTree =======================
filetype plugin indent on
let NERDTreeShowHidden=1
let NERDTreeShowLineNumbers=1
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
" ----------------------------------------
" plugin: vim-go =========================
nnoremap <leader>gi :GoImport <C-R><C-W><cr>
" ----------------------------------------
" plugin: vim-terraform ==================
let g:terraform_fmt_on_save=1
" ----------------------------------------
