source ~/.zshrc.shared
# nvm
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
# Guix
GUIX_PROFILE="/home/tkiatd/.guix-profile"
. "$GUIX_PROFILE/etc/profile"
export PATH="$HOME/.config/guix/current/bin:$PATH"
# export GUIX_PACKAGE_PATH=/mnt/shared/Git/scripts/guix/custom-packages

export SSL_CERT_DIR="$HOME/.guix-profile/etc/ssl/certs" # OpenSSL
export SSL_CERT_FILE="$HOME/.guix-profile/etc/ssl/certs/ca-certificates.crt" # OpenSSL
export GUIX_LOCPATH=$HOME/.guix-profile/lib/locale
export GIT_SSL_CAINFO="$SSL_CERT_FILE" # Git
# export CURL_CA_BUNDLE="$HOME/.guix-profile/etc/ssl/certs/ca-certificates.crt" # R
